[project]
name = "frontend"
version = "0.1.0"
description = "Frontend File Dependencies"
requires-python = ">=3.11"
dependencies = [
    "altair>=5.5.0",
    "numpy>=2.3.2",
    "pandas>=2.3.2",
    "requests>=2.32.5",
    "scikit-learn>=1.7.1",
    "streamlit>=1.49.1",
]
